language: python

cache: 
  pip: true
  directories:
    - build

python:
  - "2.7"

sudo: required

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install simhash tree pylint splint gitstats
  - pip install pre-commit gitinspector

script:
  - ./nodata.sh
  - ./analysis.sh
  - ./others.sh
  - ./total.sh
  - ./reports.sh
  - echo "http://travisatfluid.s3-website-us-east-1.amazonaws.com/training/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/people/"

addons:
  artifacts:
    debug: true
    bucket: travisatfluid
    paths:
    - ./build
