language: python

cache:
  pip: true
  directories:
    - build

python:
  - "2.7"

sudo: required

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install simhash tree pylint splint gitstats
  - pip install pre-commit gitinspector

script:
  - git diff --name-only HEAD $(git merge-base HEAD master) | xargs pre-commit run --files
  - ./url.sh
  - ./nodata.sh
  - ./analysis.sh
  - ./others.sh
  - ./total.sh
  - ./reports.sh

addons:
  artifacts:
    debug: false
    bucket: travisatfluid
    paths:
    - ./build
