language: python
python:
  - "2.7"
sudo: required
install:
  - pip install pre-commit gitinspector
  - sudo apt-get install -y simhash tree flake8 pylint ruby-lint splint gjslint shellcheck gitstats
script:
  - ./nodata.sh
  - ./analysis.sh
  - ./others.sh
  - ./total.sh
  - ./reports.sh
