language: python

cache:
  pip: true
  directories:
    - build

sudo: required
dist: trusty

group: edge

python:
  - "2.7"

before_install:
  skip

install:
  skip

jobs:
  include:
    - stage: Pre install requirements
      script: sudo add-apt-repository ppa:webupd8team/atom -y
    - script: sudo apt-get update -qq
    - stage: Install dependencies
      script: sudo apt-get install simhash tree pylint splint gitstats aspell aspell-es aptitude checkstyle cppcheck -qq
    - script: sudo apt-get -y install hlint atom  -qq
    - script: sudo aptitude install shellcheck
    - script: sudo apm install linter-eastwood
    - script: gem install cucumber ruby-lint
    - script: pip install pre-commit gitinspector scons requests flake8 https://github.com/google/closure-linter/zipball/master
    - stage: Precommit
      script: ./precommit.sh
      script: ./url.sh
      script: ./nodata.sh
    - stage: SCons Folder-check
      script: scons -j 4 folders -Q
    - stage: SCons Gherkin-build
      script: scons gherkin -Q
    - stage: SCons others-check
      script: scons others -Q

addons:
  artifacts:
    debug: false
    bucket: travisatfluid
    paths:
    - ./build
