language: python

python:
  - "2.7"

sudo: required

install:
  - pip install pre-commit gitinspector
    # flake8 ruby-lint gjslint shellcheck
  - sudo apt-get install -y simhash tree pylint splint gitstats

script:
  - ./nodata.sh
  - ./analysis.sh
  - ./others.sh
  - ./total.sh
  - ./reports.sh

addons:
  srcclr: true
