language: python

cache: 
  pip: true
  directories:
    - artifacts
    - ~/.cabal

python:
  - "2.7"

sudo: required

before_install:
  - sudo apt-get update -qq

install:
  - cabal install shellcheck
  - pip install pre-commit gitinspector
    # flake8 ruby-lint gjslint shellcheck
  - sudo apt-get install -y simhash tree pylint splint gitstats

script:
  - ./nodata.sh
  - ./analysis.sh
  - ./others.sh
  - ./total.sh
  - ./reports.sh

#addons:
#  srcclr: true
