language: python

cache:
  pip: true
  directories:
    - build

sudo: required
dist: trusty

group: edge

python:
  - "2.7"

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install simhash tree pylint splint gitstats aspell aspell-es aptitude checkstyle
  - sudo aptitude install shellcheck
  - gem install cucumber
  - gem install ruby-lint
  - pip install pre-commit gitinspector
  - pip install scons
  - pip install requests
  - pip install flake8
  - pip install https://github.com/google/closure-linter/zipball/master

script:
  - ./precommit.sh
  - ./url.sh
  - ./nodata.sh
  - scons folders
  - scons gherkin
  - scons others
  - ./total.sh
  - ./reports.sh

addons:
  artifacts:
    debug: false
    bucket: travisatfluid
    paths:
    - ./build
