language: python
python:
  - "2.7"
sudo: required
install:
  - pip install pre-commit
  - apt-get install -y simhash tree
script:
  - nodata.sh
  - analysis.sh
  - others.sh
  - total.sh
  - reports.sh
