language: python
python:
  - "2.7"
sudo: required
install:
  - "pip install pre-commit"
  - sudo apt-get install -y simhash
script:
  - bash nodata.sh
  - bash analysis.sh
  - bash others.sh
  - bash total.sh
  - bash report.sh
